---
RecipeFormatVersion: "2020-01-25"
ComponentName: "COMPONENT_NAME"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This is a component to update OS."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    update_no: "/tmp/update_1"
Manifests:
  - Platform:
      os: linux
      architecture: aarch64
    Lifecycle:
      run:
        RequiresPrivilege: true
        Script: |-
          # if there is no {configuration:/update_no}, this is the 1st time
          if [ ! -f {configuration:/update_no} ] ; then
            touch {configuration:/update_no}

            # Write your commands
            apt-get update
            # shutdown -r now
          else
            echo "Already updated."
          fi