---
RecipeFormatVersion: "2020-01-25"
ComponentName: "COMPONENT_NAME"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This is certificate rotator application component written in Python that run in Docker container."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    lambda_csr_res_topic: "lambda/+/csr_res"
    lambda_crt_ack_topic: "lambda/+/crt_ack"
    device_csr_req_topic: "device/+/csr_req"
    device_crt_topic: "device/+/crt"
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        com.CertificateRotatorApp:mqttproxy:1:
          policyDescription: "Allows access to subscribe to input topics."
          operations:
            - "aws.greengrass#SubscribeToIoTCore"
          resources:
            - "device/+/csr_req"
            - "device/+/crt"
        com.CertificateRotatorApp:mqttproxy:2:
          policyDescription: "Allows access to publish to output topics."
          operations:
            - "aws.greengrass#PublishToIoTCore"
          resources:
            - "lambda/+/csr_res"
            - "lambda/+/crt_ack"
ComponentDependencies:
  aws.greengrass.DockerApplicationManager:
    VersionRequirement: ~2.0.0
  aws.greengrass.TokenExchangeService:
    VersionRequirement: ~2.0.0
Manifests:
  - Platform:
      os: linux
      architecture: aarch64
    Lifecycle:
      run: 
        RequiresPrivilege: true
        Script: |-
          docker stop COMPONENT_NAME || true
          docker rm COMPONENT_NAME || true
          docker run --name COMPONENT_NAME \
            -e LAMBDA_CSR_RES_TOPIC=\"{configuration:/lambda_csr_res_topic}\" \
            -e LAMBDA_CRT_ACK_TOPIC=\"{configuration:/lambda_crt_ack_topic}\" \
            -e DEVICE_CSR_REQ_TOPIC=\"{configuration:/device_csr_req_topic}\" \
            -e DEVICE_CRT_TOPIC=\"{configuration:/device_crt_topic}\" \
            -e SVCUID \
            -e AWS_GG_NUCLEUS_DOMAIN_SOCKET_FILEPATH_FOR_COMPONENT \
            -v $AWS_GG_NUCLEUS_DOMAIN_SOCKET_FILEPATH_FOR_COMPONENT:$AWS_GG_NUCLEUS_DOMAIN_SOCKET_FILEPATH_FOR_COMPONENT \
            -v /bin/systemctl:/bin/systemctl \
            -v /run/systemd/system:/run/systemd/system \
            -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket \
            -v /greengrass/v2:/greengrass/v2 \
            --device /dev/gpiomem \
            --privileged \
            AWS_ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/COMPONENT_NAME_repository@DIGEST
    Artifacts:
      - URI: "docker:AWS_ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/COMPONENT_NAME_repository:latest"
